const column =[
  {id:'rn', active:true, name:'No'},
    {id:'site', active:true, name:'Site'},
    {id:'client', active:true, name:'Client'},
    {id:'orderno', active:true, name:'Order No'},
    {id:'ordertype', active:true, name:'Order Type'},
    {id:'isistask', active:true, name:'Task'},
    {id:'customername', active:true, name:'Customer'},        
    {id:'status', active:true, name:'Status'},
    {id:'deliverydate', active:true, name:'Delivery Date'},
    {id:'datereceived', active:true, name:'Date Received'},
    {id:'datereleased', active:true, name:'Date Released'},
    {id:'datecompleted', active:true, name:'Date Completed'},
    {id:'customerpono', active:false, name:'Customer Po Ref'},
    {id:'vendororderno', active:false, name:'Vendor Order Ref'},
    {id:'address1', active:false, name:'Address 1'},
    {id:'address2', active:false, name:'Address 2'},
    {id:'address3', active:false, name:'Address 3'},
    {id:'address4', active:false, name:'Address 4'},
    {id:'address5', active:false, name:'Address 5'},
    {id:'suburb', active:false, name:'Suburb'},
    {id:'postCode', active:false, name:'Post Code'},
    {id:'state', active:false, name:'State'},
    {id:'country', active:false, name:'Country'},
    {id:'loadnumber', active:false, name:'Load Number'},
    {id:'loadoutstart', active:false, name:'Loadout Start'},
    {id:'loadoutfinish', active:false, name:'Loadout Finish'},
    {id:'consignmentno', active:false, name:'Consigment No'},
    {id:'freightcharge', active:false, name:'Freight Charge'},
    {id:'customer', active:false, name:'Customer Code'},
  ]

  export {column}