const column =[
    {id:'site', active:true, name:'Site'},
    {id:'client', active:true, name:'Client'},
    {id:'orderNo', active:true, name:'Order No'},
    {id:'orderType', active:true, name:'Order Type'},
    {id:'customerName', active:true, name:'Customer'},        
    {id:'status', active:true, name:'Status'},
    {id:'deliveryDate', active:true, name:'Delivery Date'},
    {id:'dateReceived', active:true, name:'Date Received'},
    {id:'dateReleased', active:true, name:'Date Released'},
    {id:'dateCompleted', active:true, name:'Date Completed'},
    {id:'customerPoNo', active:false, name:'Customer Po Ref'},
    {id:'vendorOrderNo', active:false, name:'Vendor Order Ref'},
    {id:'address1', active:false, name:'Address 1'},
    {id:'address2', active:false, name:'Address 2'},
    {id:'address3', active:false, name:'Address 3'},
    {id:'address4', active:false, name:'Address 4'},
    {id:'address5', active:false, name:'Address 5'},
    {id:'suburb', active:false, name:'Suburb'},
    {id:'postCode', active:false, name:'Post Code'},
    {id:'state', active:false, name:'State'},
    {id:'country', active:false, name:'Country'},
    {id:'loadNumber', active:false, name:'Load Number'},
    {id:'loadoutStart', active:false, name:'Loadout Start'},
    {id:'loadoutFinish', active:false, name:'Loadout Finish'},
    {id:'consignmentNo', active:false, name:'Consigment No'},
    {id:'freightCharge', active:false, name:'Freight Charge'},
    {id:'customer', active:false, name:'Customer Code'},
  ]

  export {column}