export const dummyData = [
    { 
        site: 'A', 
        client: 'BEGA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'B', 
        client: 'BEGA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'E', 
        client: 'BEGA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'L', 
        client: 'BEGA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'A', 
        client: 'TATURA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'B', 
        client: 'TATURA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'E', 
        client: 'TATURA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'L', 
        client: 'BEGA', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'A', 
        client: 'ANTEC', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'B', 
        client: 'ANTEC', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'E', 
        client: 'ANTEC', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'L', 
        client: 'ANTEC', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },
    { 
        site: 'A', 
        client: 'ANTEC', 
        order_no: 'AM2020007P0001', 
        order_type: 'RKWN', 
        isis_task: 'RKWN', 
        supplier_no: '123', 
        supplier_name: 'Intervace', 
        status: 'AvaiLable' ,
        delivery_date: '07/09/2020', 
        date_received: '07/09/2020', 
        date_released: '07/09/2020', 
        date_completed: '07/09/2020' 
    },

]

export const schemaColumn = [
    {
        Header: 'Site',
        accessor: 'site',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 500,
    },
    {
        Header: 'Client',
        accessor: 'client',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 500
    },
    {
        Header: 'Order NO',
        accessor: 'order_no',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Order Type',
        accessor: 'order_type',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Task',
        accessor: 'isis_task',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Supplier No',
        accessor: 'supplier_no',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Supplier Name',
        accessor: 'supplier_name',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Status',
        accessor: 'status',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Order Date',
        accessor: 'delivery_date',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Date Received',
        accessor: 'date_received',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Date Released',
        accessor: 'date_released',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
    {
        Header: 'Date Completed',
        accessor: 'date_completed',
        headerStyle: { textAlign: 'left' },
        style: { textAlign: 'left', paddingLeft: '15px' },
        headerClassName: 'borderBottom noPaddingTop',
        sortable: true,
        width: 800
    },
]