name: Dev Action
on:
  push:
    branches:
      - dev/latest
  pull_request:
    branches:
      - dev/latest
env:
  IMAGE_VERSION: 1.0
jobs:
  prepare-to-deploy:
    name: Prepare to Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t rzldevdoc/microlistics-fe-dev:$IMAGE_VERSION -f Dockerfile.dev .
      - name: Push docker image
        run: docker push rzldevdoc/microlistics-fe-dev:$IMAGE_VERSION
      - name: Build docker image latest
        run: docker build -t rzldevdoc/microlistics-fe-dev:latest -f Dockerfile.dev .
      - name: Push docker image latest
        run: docker push rzldevdoc/microlistics-fe-dev:latest

---
name: UAT Action
on:
  push:
    branches: 
      - refactor-v1.3
  pull_request:
    branches:
      - refactor-v1.3
env:
  IMAGE_VERSION: 1.0
jobs:
  push-to-docker:
    name: Push to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t rzldevdoc/microlistics-fe-uat:$IMAGE_VERSION -f Dockerfile.uat .
      - name: Push docker image
        run: docker push rzldevdoc/microlistics-fe-uat:$IMAGE_VERSION
      - name: Build docker image latest
        run: docker build -t rzldevdoc/microlistics-fe-uat:latest -f Dockerfile.uat .
      - name: Push docker image latest
        run: docker push rzldevdoc/microlistics-fe-uat:latest

---
name: Prod Action
on:
  push:
    branches:
      - feature/preparing-release-v1
  pull_request:
    branches:
      - feature/preparing-release-v1
env:
  IMAGE_VERSION: 1.0
jobs:
  push-to-docker:
    name: Push to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t rzldevdoc/microlistics-fe-prod:$IMAGE_VERSION -f Dockerfile.prod .
      - name: Push docker image
        run: docker push rzldevdoc/microlistics-fe-prod:$IMAGE_VERSION
      - name: Build docker image latest
        run: docker build -t rzldevdoc/microlistics-fe-prod:latest -f Dockerfile.prod .
      - name: Push docker image latest
        run: docker push rzldevdoc/microlistics-fe-prod:latest
