---
name: Dev Action
on:
  push:
    branches:
      - dev/latest
  pull_request:
    branches:
      - dev/latest
env:
  IMAGE_VERSION: 1.0
jobs:
  prepare-to-deploy:
    name: Prepare to Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t rzldevdoc/microlistics-fe-dev:$IMAGE_VERSION -f Dockerfile.dev .
      - name: Push docker image
        run: docker push rzldevdoc/microlistics-fe-dev:$IMAGE_VERSION
      - name: Build docker image latest
        run: docker build -t rzldevdoc/microlistics-fe-dev:latest -f Dockerfile.dev .
      - name: Push docker image latest
        run: docker push rzldevdoc/microlistics-fe-dev:latest
