---
name: Dev Action
on:
  push:
    branches:
      - dev/latest
  pull_request:
    branches:
      - dev/latest
env:
  IMAGE_VERSION: "1.0"
  IMAGE_TAG: rzldevdoc/microlistics-fe:dev-1.0
jobs:
  prepare-to-deploy:
    name: Prepare to Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image ${{ env.IMAGE_VERSION }} & latest
        run: docker build -t ${{ env.IMAGE_TAG }} -t rzldevdoc/microlistics-fe:dev-latest -f Dockerfile.dev .
      - name: Push docker image ${{ env.IMAGE_VERSION }}
        run: docker push ${{ env.IMAGE_TAG }}
      - name: Push docker image latest
        run: docker push rzldevdoc/microlistics-fe:dev-latest
